# Generated by Django 4.0.5 on 2022-08-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_portal_publisher_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_headline',
        ),
    ]
